language: node_js
sudo: false
node_js: stable
addons: 
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin local
env:
  global:
  - secure: GfrBkT6GMBBWmseT94rXApSzwLJjXM1ogpG8CIiKxL5ZiekbD0I3PGz/RRTQ2qZOyVGqmiSmBBRIMJO28FgGKbPRTidUsI1j2Tb7yI26MO/WVHZ5KXG21ll3Rg/ZA+wJHq09iYWTX+03cYcOYRh0xnLgb+NKKdg4AJEnXFKe95Eb5RtT0+PvV4BucVpMbGkNtkm3YtjxFILOnpJYm5lSinfe5oITpO9P5ZFQaOeUh8Is4LxLIPBFc7lt0/aWuRvFM7O7fCR6QRtR8E7fGfXw+Gp6va2QQUgT2SFuMSox2xfuHjfh2JAuIdIiSaXZaPfwWiJW/RUFI4ZpBeukNmk7+BsmNxW2LPGQQwbDs9OK9CjI6iP8y2qr/Iurxlfuf6LtYpj8ad83uxwc+pReVddHFsaSpfNRTXNDL26KXkVDdavzvgUl8DqUNXJW1J79BsVd57OwyhNSLzQSBKp7nrAnyHKra1j4YfshJivpPitzk2+zru6nu2F77UXPzHy/3FDSbqDEO2464Mp7n3oe37yx8QtwJU45OedAIIQTcPdrjw6NIDuRo0+OoAVkx+cTe6yO4eh6PoCCZHCW0gABMz5R9nhiozFdt5Pxw62pe0ZzYmyCOhq9yRm37SpB2M29b4uXfjOVoZTaJ76cgOQtBUjBr1a55rlc/0lbqdjOqVQ4TbA=
  - secure: brlrpOCewKziBFaVijnVVk25VUD8WdREJVuCptcT3Lu6l4rLaAphLBE9CFlvciYROLIqN8IIhvdzARL1NqKXi48YYe8b1lZju7mSSerNy+qkNglnKYN7P+oxkMG2gkb6J7zmPdKu1PQOYrXXgepsrGhWb4dwPKzEtfGGtzJmfzHvnphx23QUAoJi1ECKlM1EP4hpHn49Fae4YXKn6XH7BIme3hyP0rahpsFlsvtQUU4KYc+onKUZGmFDBMcGKj9/3bMGxkC2UIvY+9Rj3zZ5zH6pXzY7wOjQQ+0Tzw3xu0sgfh7ecNc46sgQBS7PyI6oFBY2gDGwmyj4IloUxCkwhSWlIErYqjOVstgNwix0p/yDuIaVmrUY6yubHPml9/8mGsb2mFqbmVv7eH8Z1MZPjUg90y3r1zXIh727ql8D3oS2c2tCL4SyLYGHsTvLwx9v6//xT1KCwdkFnzZchgvtyLob4yKHiFWmWjgC6aCg3PLu2qBjsjHQj9Ze+a4jNAVcqVPma6si4bIw/dUvanEGU3oE2ZnrkOu8WlwjASlplQmHvc85FE8IAJ2QqHQplhlAV8uOiN9wV0bu5HcSm4d+84K92vyqFEygXarNw5wDs9Ld0+ARpBKApr+E01xwpLMKAft8GDNN+aPDpbM/hbQ6RCgIg4nliYhPEOm8LEz7ATs=
